#include <GothicFunctions.h>

ZCVobDoFrameActivity zCVobDoFrameActivity = (ZCVobDoFrameActivity)ZCVOB_DO_FRAME_ACTIVITY_ADDRESS;
ZCVobSetPhysicsEnabled zCVobSetPhysicsEnabled = (ZCVobSetPhysicsEnabled)ZCVOB_SET_PHYSICS_ENABLED_ADDRESS;
OCGamePause oCGamePause = (OCGamePause)OCGAME_PAUSE_ADDRESS;
OCGameUnpause oCGameUnpause = (OCGameUnpause)OCGAME_UNPAUSE_ADDRESS;

ZCVobSetCollDet zCVobSetCollDet = (ZCVobSetCollDet)ZCVOB_SET_COLL_DET_ADDRESS;
ZCAIPlayerCheckFloorSliding zCAIPlayerCheckFloorSliding = (ZCAIPlayerCheckFloorSliding)ZCAIPLAYER_CHECK_FLOOR_SLIDING_ADDRESS;

DoSurfaceAlignment doSurfaceAlignment = (DoSurfaceAlignment)DO_SURFACE_ALIGNMENT_ADDRESS;
ZCVobCheckAndResolveCollisions zCVobCheckAndResolveCollisions = (ZCVobCheckAndResolveCollisions)ZCVOB_CHECK_AND_RESOLVE_COLLISION_ADDRESS;

ZCTriggerOnTouch zCTriggerOnTouch = (ZCTriggerOnTouch)ZCTRIGGER_ON_TOUCH_ADDRESS;
ZCVobHasEnoughSpace zCVobHasEnoughSpace = (ZCVobHasEnoughSpace)ZCVOB_HAS_ENOUGH_SPACE_ADDRESS;

ZCVobGetVelocity zCVobGetVelocity = (ZCVobGetVelocity)ZCVOB_GET_VELOCITY_ADDRESS;
ZCVobBeginMovement  zCVobBeginMovement = (ZCVobBeginMovement)ZCVOB_BEGIN_MOVEMENT_ADDRESS;

OCNpcIsMovLock oCNpcIsMovLock = (OCNpcIsMovLock)OCNPC_IS_MOV_LOCK_ADDRESS;
ZCModelCalcModelBBox3DWorld zCModelCalcModelBBox3DWorld = (ZCModelCalcModelBBox3DWorld)ZCMODEL_CALC_MODEL_BBOX3D_WORLD_ADDRESS;

ZCAIPlayerCheckEnoughSpaceMoveDir zCAIPlayerCheckEnoughSpaceMoveDir = (ZCAIPlayerCheckEnoughSpaceMoveDir) ZCAIPLAYER_CHECK_ENOUGH_SPACE_MOVE_DIR_ADDRESS;
OCAIHumanPC_ActionMove oCAIHumanPC_ActionMove = (OCAIHumanPC_ActionMove)OCAIHUMAN_PC_ACTION_MOVE_ADDRESS;

ZCCollObjectCharacterCalcSlideVector zCCollObjectCharacterCalcSlideVector = (ZCCollObjectCharacterCalcSlideVector)ZCCOLL_OBJECT_CHARACTER_CALC_SLIDE_VECTOR_ADDRESS;
ZMAT4SetTranslation zMAT4SetTranslation = (ZMAT4SetTranslation)ZMAT4_SET_TRANSLATION_ADDRESS;

ZCVobCalcGroundPoly zCVobCalcGroundPoly = (ZCVobCalcGroundPoly)ZCVOB_CALC_GROUND_POLY_ADDRESS;
ZCVobUpdatePhysics zCVobUpdatePhysics = (ZCVobUpdatePhysics)ZCVOB_UPDATE_PHYSICS_ADDRESS;

ZCVobEndMovement zCVobEndMovement = (ZCVobEndMovement)ZCVOB_END_MOVEMENT;
TestStatic_Char_Char testStatic_Char_Char = (TestStatic_Char_Char)TESTSTATIC_CHAR_CHAR_ADDRESS;

ZCCollObjectCharacterTestSoftCollisions zCCollObjectCharacterTestSoftCollisions = (ZCCollObjectCharacterTestSoftCollisions)ZCCOLL_OBJECT_CHARACTER_TEST_SOFT_COLLIONS_ADDRESS;
ZCCollObjectCharacterTestHardCollisions zCCollObjectCharacterTestHardCollisions = (ZCCollObjectCharacterTestHardCollisions)ZCCOLL_OBJECT_CHARACTER_TEST_HARD_COLLIONS_ADDRESS;

ZCCollObjectCharacterDetectCollisionsSelf zCCollObjectCharacterDetectCollisionsSelf = (ZCCollObjectCharacterDetectCollisionsSelf)ZCCOLL_OBJECT_CHARACTER_DETECT_SELF_COLLISION_ADDRESS;
ZCAIPlayerCheckPhysics zCAIPlayerCheckPhysics = (ZCAIPlayerCheckPhysics)ZCAIPLAYER_CHECK_PHYSICS;

ZCCollObjectCharacterFindFloorWaterCeiling zCCollObjectCharacterFindFloorWaterCeiling = (ZCCollObjectCharacterFindFloorWaterCeiling)ZCCOLL_OBJECT_CHARACTER_FIND_FLOOR_WATER_CEILING;
OCItemContainerDrawCategory oCItemContainerDrawCategory = (OCItemContainerDrawCategory)OCITEM_CONTAINER_DRAW_CATEGORY_ADDRESS;

OCItemContainerGetSelectedItem oCItemContainerGetSelectedItem = (OCItemContainerGetSelectedItem)0x007092C0;